CREATE TABLE IF NOT EXISTS Pokemon (
    POKEID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME varchar(255),
    POKEDEXNUMBER INT
);

CREATE TABLE IF NOT EXISTS PokemonCaught (
    POKEID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME varchar(255),
    POKEDEXNUMBER INT
);